### ISSUE TITLE
Extension loading error

### ISSUE THREAD

**Issue by 157946a** [PlaceholderAPI/Server-Expansion#45] opened 2022-04-25 23:09 UTC
```
[07:06:09 ERROR]: [PlaceholderAPI] failed to load class files of expansions
java.util.concurrent.CompletionException: java.lang.ClassNotFoundException: com.extendedclip.papi.expansion.server.caffeine.cache.LocalCacheFactory$SSEMWW
        at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$findExpansionInFile$4(LocalExpansionManager.java:326) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:1.8.0_301]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[?:1.8.0_301]
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_301]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_301]
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_301]
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_301]
Caused by: java.lang.ClassNotFoundException: com.extendedclip.papi.expansion.server.caffeine.cache.LocalCacheFactory$SSEMWW
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_301]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
        at me.clip.placeholderapi.util.FileUtil.findClass(FileUtil.java:63) ~[?:?]
        at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$findExpansionInFile$4(LocalExpansionManager.java:319) ~[?:?]
        ... 6 more
```
As long as there is a server extension in placeholderapi/expansions, the above error will inevitably appear, resulting in the failure of other variable expansions, deletion is normal, and tested

**Comment by Andre601** [comment] 2022-04-25 23:22
Duplicate of #44

**Closed by Andre601** 2022-04-25 23:22 UTC

**Comment by 157946a** [comment] 2022-04-26 03:27
Why close, you didn't solve my problem at all

**Comment by 157946a** [comment] 2022-04-26 03:31
https://paste.helpch.at/ujufulitac
He also provided more information, including papi dump, this is mine now, why did you close it

**Comment by darbyjack** [comment] 2022-04-26 04:00
It was closed because there is already an open ticket related to this issue.

**Comment by 157946a** [comment] 2022-04-26 04:02
Then you solve my problem and show him

**Comment by 157946a** [comment] 2022-04-26 04:39
I tried to download the old version. After downloading, it became the latest version of 2.6.1 after restarting, and then the error was reported again.

**Comment by darbyjack** [comment] 2022-04-26 04:40
We're aware of the problem and are working on a solution. Thank you for your patience.
