### ISSUE TITLE
MSPT placeholder

### ISSUE THREAD

**Issue by BlitzOffline** [PlaceholderAPI/Server-Expansion#40] opened 2021-12-12 14:56 UTC
Someone in helpchat was suggesting an MSPT placeholder that would return the value that Server#getAverageTickTime() returns. The only issue is that its only available in paper and its forks so it might create some confusion if listed on the wiki and it only works on some servers.

**Comment by srnyx** [comment] 2022-01-21 23:31
Duplicate of https://github.com/PlaceholderAPI/Server-Expansion/issues/7

**Closed** 2022-01-21 23:33 UTC
